add_newline = true
command_timeout = 200

format = """$directory$git_branch$git_status\n$character"""

[directory]
style = "cyan"
truncate_to_repo = false
truncation_length = 1
truncation_symbol = "…/"  # optional, similar to your ZSH

[git_branch]
format = "[git:([$branch](red))]($style)"
style = "blue"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "yellow"
conflicted = "✗"
ahead = ""
behind = ""
diverged = ""
stashed = ""
staged = ""
untracked = ""
modified = "✗"
renamed = ""
deleted = ""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "
vicmd_symbol = "[➜](bold purple) "
